name: deploy gh-pages
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'example/**'
jobs:
  build:
    name: Build and deploy gh-pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: |
          yarn
      - name: run build
        run: |
          yarn doc:github-build
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npx gh-pages -d docs-dist -u "github-actions-bot <support+actions@github.com>"
          echo 🤘 deploy doc-pages complete.
        env:
          GITHUB_TOKEN: ${{ github.token }}
